[package]
name = "flscolors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.0"
const_format = "0.2.32"
nom = "7.1.3"
