[package]
name = "flscolors-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "flscolors-cli"
bench = false

[dependencies]
flscolors = { path = "../flscolors" }
clap = { version = "4.4.16", features = ["derive"] }
